### ISSUE TITLE
Simple storage network tripling some items visually

### ISSUE THREAD

**Issue by aminecraftplayer2** [Iskallia/Vault-public#1221] opened 2023-03-20 09:23 UTC
**Describe the bug**
A visual glitch where SSN is tripling some items visually, including unstackaqble ones
**To Reproduce**
1.
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
I
![image](https://user-images.githubusercontent.com/128365841/226297693-c31330c7-f355-4962-bcee-acded932722b.png)

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server]
- The_Vault Version 1.18

**Additional context**

**Comment by d0zzer2** [comment] 2023-03-21 13:28
This is a SSN issue not VH. With that being said, chests and double chests can only have one cable attached to them or you get issues like this.

**Comment by BraveCaperCat2** [comment] 2023-05-05 19:55
Duplicate of #1220

**Closed as completed** 2023-05-05 22:22 UTC
