### ISSUE TITLE
Infinite Boss Crates

### ISSUE THREAD

**Issue by DevCorp-beta** [Iskallia/Vault-public#161] opened 2021-03-31 10:34 UTC
**Describe the bug**
Infinite Boss crates and vault timer breaks

**To Reproduce**
1.find a boss room
2.kill a boss
3.eat pear
4.find another boss room and repeat
after killing the boss once then the vault timer never will decrease even after killing the boss multiple times

**Expected behavior**
Donno

**Screenshots or Crash Report**
![image](https://user-images.githubusercontent.com/64924939/113131243-a3885c00-9225-11eb-8bc8-c049d40bb46a.png)

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version [e.g. 1.0.1]

**Additional context**

**Comment by ImreBoersma** [comment] 2021-03-31 10:56
Dupe of #111. Dev team said they're going to fix this

**Closed** 2021-03-31 13:15 UTC
Labels: duplicate
