### ISSUE TITLE
Having only 2 Actives unlocked makes it unable to access the Wheel to select them.

### ISSUE THREAD

**Issue by Enderized** [Iskallia/Vault-public#29] opened 2021-03-25 13:57 UTC
And therefore you cannot swap e.g. Ghostwalk for Megajump if you only have these two.
https://youtu.be/_FZE_Hm8nHU
(am pressing Left Alt repeatedly before leveling into mega jump)

After learning a 3rd ability it works just fine

**Comment by BONNe** [comment] 2021-03-25 14:48
I run into the same issue. It looks like it just does not open or switches abilities if you have any 2 unlocked.

This happens still in 1.0.1 version.

**Comment by iskall85** [comment] 2021-03-25 15:45
This is working as intended. The ability wheel will only activate after 3 or more abilities. WAI closing the report

**Closed by iskall85** 2021-03-25 15:45 UTC

**Comment by BONNe** [comment] 2021-03-25 15:59
Iskall, I have a question, how to change abilities?
