### ISSUE TITLE
Game crashes when opening advanced vending machine

### ISSUE THREAD

**Issue by EwokHero** [Iskallia/Vault-public#15] opened 2021-03-25 10:10 UTC
[crash-2021-03-25_11.07.16-client.txt](https://github.com/Iskallia/Vault-public/files/6203827/crash-2021-03-25_11.07.16-client.txt)

**Comment by Nimothy** [comment] 2021-03-25 10:12
Hi @EwokHero, thank you for reporting this, it is a duplicate of #10 please can you close this and instead put a comment on that issue, detailing the log which you provided and how you acquired the trading core?

**Closed** 2021-03-25 10:23 UTC
