### ISSUE TITLE
Vualt Gear stuck in ME system

### ISSUE THREAD

**Issue by HoogaSwe** [Iskallia/Vault-public#175] opened 2021-04-01 15:34 UTC
**Describe the bug**
Placed a Vault dagger and vault Boots in a ME system and now i cant take it out.

**Expected behavior**
Vault dagger taken out. 

**Screenshots or Crash Report**
![image](https://user-images.githubusercontent.com/81357122/113318043-5339f880-9310-11eb-9316-b3a18b555701.png)

**Info (please complete the following information):**
- World Type: Kumara

**Additional context**

**Comment by iGoodie** [comment] 2021-04-01 15:36
Duplicate of #118

**Closed by iGoodie** 2021-04-01 15:36 UTC
