### ISSUE TITLE
All zombies have 2 swords

### ISSUE THREAD

**Issue by LexLogs** [Iskallia/Vault-public#55] opened 2021-03-26 03:15 UTC
All Zombies/Skeletons/ Pillagers in the vault have 2 swords, tested in 2 different worlds and multiple crystals. Only effects levels 0-29 once you pass level 30 it stops
![2021-03-25_20 12 16](https://user-images.githubusercontent.com/81400282/112572162-cf7b8b80-8da6-11eb-8b5a-70ee158b7988.png)
![2021-03-25_20 40 19](https://user-images.githubusercontent.com/81400282/112574014-abba4480-8daa-11eb-8aee-fdadab135fc5.png)
![2021-03-25_20 41 25](https://user-images.githubusercontent.com/81400282/112574026-b07ef880-8daa-11eb-95cb-257309cf945f.png)

**Comment by bmemike** [comment] 2021-03-26 12:35
Dupe of #44

**Closed** 2021-03-30 00:36 UTC
