### ISSUE TITLE
Crash on placing lilypad

### ISSUE THREAD

**Issue by BONNe** [Iskallia/Vault-public#42] opened 2021-03-25 19:59 UTC
#### Describe the bug

The client crashes when placing tiny lilypads in the water.

#### Steps to reproduce the behavior

1. Get a tiny lilypad
2. Place it in the water

#### Screenshots and videos (Optional)

 
[crash-2021-03-25_21.53.47-client.txt](https://github.com/Iskallia/Vault-public/files/6207496/crash-2021-03-25_21.53.47-client.txt)

### Additional context (Optional)

Looks like some easter egg code is not working properly.

**Comment by Nimothy** [comment] 2021-03-25 20:21
Hi @BONNe , looks like this is a duplicate of #41, let's commit add a comment with this really useful information there.

**Closed** 2021-03-25 21:12 UTC
