### ISSUE TITLE
Common Trader Loottables issue

### ISSUE THREAD

**Issue by Dark-Ducky** [Iskallia/Vault-public#9] opened 2021-03-25 08:24 UTC
there are many issue with traders loottables 
1.trader selling elytra is selling 32 eltytas for 6 vault gold
2.trader selling 1 vault gold for 5 vault gold 
3.Buy id missing for vault gold and vault platinum
![vault gold](https://user-images.githubusercontent.com/81279900/112442262-aa205a80-8d71-11eb-9d0b-09487fd80382.png)
![Elytra loottable wrong](https://user-images.githubusercontent.com/81279900/112442267-abea1e00-8d71-11eb-8db8-624cbb0de64d.png)
![buy id missing](https://user-images.githubusercontent.com/81279900/112442269-abea1e00-8d71-11eb-94e6-233ce61765f4.png)

**Comment by Nimothy** [comment] 2021-03-25 08:28
Hi @Dark-Ducky, this looks to be a duplicate of #7 , can you please close this and instead put a comment on that issue?

**Closed** 2021-03-25 08:43 UTC
