### ISSUE TITLE
Phoenix Not restoring Items

### ISSUE THREAD

**Issue by THATTHING05** [Iskallia/Vault-public#521] opened 2021-10-26 04:28 UTC
**Describe the bug**
After killing a vault boss, I died before the teleport. Phoenix was ignored, and all items were cleared.

**To Reproduce**
1.Enter a Phoenix Vault
2.Kill the boss
3.Die before the teleport "/kill works too"

**Expected behavior**
Phoenix should restore items upon death

- World Type: [Single Player]
- The_Vault Version [1.6.2]

Issue #444 and #515 have the same issue

**Comment by bmemike** [comment] 2021-10-26 13:24
Dupe of #444

**Comment by jmilthedude** [comment] 2021-10-31 03:55
This will no longer be an issue in the next update in which, after you kill the boss, you will no longer be able to take damage until you return to the overworld.

**Closed as completed by jmilthedude** 2021-10-31 03:55 UTC

**Comment by THATTHING05** [comment] 2021-11-01 04:28
Thanks for the help.
