### ISSUE TITLE
vault timer

### ISSUE THREAD

**Issue by toinedeman** [Iskallia/Vault-public#11] opened 2021-03-25 09:18 UTC
hi, i enterd a vault and the times didnt count down

**Comment by scalda** [comment] 2021-03-25 09:19
this is a duplicate of [issue 6](https://github.com/Iskallia/Vault-public/issues/6)

**Comment by toinedeman** [comment] 2021-03-25 09:20
that one was when you kild a bos but i got in when entering or is that stil the same?

**Comment by scalda** [comment] 2021-03-25 09:21
it's all connected

**Comment by toinedeman** [comment] 2021-03-25 09:21
k thanks :)

**Comment by KaptainWutax** [comment] 2021-03-25 13:05
Fixed in 1.0.1.

**Closed by KaptainWutax** 2021-03-25 13:05 UTC
Labels: duplicate
