### ISSUE TITLE
Treasure room doors can be opened using a redstone signal

### ISSUE THREAD

**Issue by magicalex234** [Iskallia/Vault-public#167] opened 2021-03-31 21:30 UTC
**Describe the bug**
Pretty self explanatory: you can use levers, pressure plates, or any other redstone signal to open treasure room doors

**To Reproduce**
1. Find a treasure room door (any gem will work, and can be manually placed, or generated by the vault)
2. Apply a redstone signal to the door
3. The door will open

**Expected behavior**
The treasure room doors should only open when the corresponding key is used on it, and no other way.

**Info (please complete the following information):**
- World Type: single player
- The_Vault Version  1.0.1

**Comment by jmilthedude** [comment] 2021-03-31 22:01
duplicate of #149

**Closed** 2021-03-31 22:02 UTC
