### ISSUE TITLE
Redstoner

### ISSUE THREAD

**Issue by sarasven585** [Iskallia/Vault-public#252] opened 2021-04-13 07:11 UTC
**Describe the bug**

**To Reproduce**
1. RFToolsBase Machine Base is underneath World Developer i say it should be underneath Redstoner because it’s used in wireless redstone
2.
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server]
- The_Vault Version [e.g. 1.0.1]

**Additional context**

**Comment by Enderized** [comment] 2021-04-14 06:24
duplicate of #226

**Closed** 2021-04-15 10:03 UTC
Labels: duplicate
