### ISSUE TITLE
Vault platinum trade

### ISSUE THREAD

**Issue by Peskybirdofdoom** [Iskallia/Vault-public#245] opened 2021-04-12 01:10 UTC
**Describe the bug**
The vault platinum trade for 50 vault gold per vault platinum is unbalanced

**To Reproduce**
Roll enough trader cores to eventually get this trade.

**Expected behavior**
The cost should probably be a lot less

**Screenshots or Crash Report**
![Screenshot (236)](https://user-images.githubusercontent.com/81360100/114328325-75304800-9b66-11eb-8b7f-6f91faebaefa.png)

**Info (please complete the following information):**
- World Type: singleplayer
- The_Vault Version 1.2

**Additional context**

**Comment by magicalex234** [comment] 2021-04-12 06:26
I can’t say for sure, but I think this is another troll (similar to the Pandora’s boxes having donkey heads in their loot tables, but I think that got removed)
There’s also a 5 gold to 1 platinum trade, so it’s not a typo either, as they both exist.
But I can’t say for sure

**Comment by Enderized** [comment] 2021-04-12 08:52
duplicate of #181

working as intended

**Closed** 2021-04-13 01:11 UTC
