### ISSUE TITLE
Afterlife crystal did not restore items after boss kill

### ISSUE THREAD

**Issue by SakiRider** [Iskallia/Vault-public#515] opened 2021-10-24 19:32 UTC
**Describe the bug**
A applied afterlife to my vault crystal. I am level 24. I defeated the boss with only one heart remaining. Has the teleport timer reached 0, I was hit by a zombie. My death screen was back in my base which makes me think I got hit has I teleported. Even though afterlife was applied. I did not respawn with any of my equipment or items. 

**To Reproduce**
1. Afterlife crystal
2. Defeat boss
3. Die as you teleport back to base
4.

**Expected behavior**
Since I teleported, I expected to complete the vault with all my items and boss crate. However, if I died just as I teleported, I should at least have had my equipment items restored to their pre-vault status.

**Screenshots or Crash Report**
I have no screen shots or crash report

**Info (please complete the following information):**
- Sparks Canada 9 server
- The_Vault Version 1.6.2

**Additional context**

**Comment by bmemike** [comment] 2021-10-25 00:39
Dupe of #444

**Comment by jmilthedude** [comment] 2021-10-31 03:59
This is fixed in the next update. see #444

**Closed as completed by jmilthedude** 2021-10-31 03:59 UTC
