### ISSUE TITLE
Dupe Armour

### ISSUE THREAD

**Issue by DraamaQ** [Iskallia/Vault-public#62] opened 2021-03-26 08:01 UTC
Are playing on iGoodie server, and we get duped armour when you rightclick armour you have equipped

**Comment by Nimothy** [comment] 2021-03-26 08:06
Hi @DraamaQ, this looks like it's a duplicate of #27.
If it is, please see Iskall's comment.

**Comment by DraamaQ** [comment] 2021-03-26 08:08
Looks like it is, okay, thank you

**Closed** 2021-03-26 08:08 UTC
