### ISSUE TITLE
64 deepslate for 1 railing brick wall

### ISSUE THREAD

**Issue by foolish4201** [Iskallia/Vault-public#1133] opened 2022-11-30 08:19 UTC
64 deepslate for 1 railing brick wall

**To Reproduce**
1. yes 
2. yes
3. yes
4. yes

**Expected behavior**
A clear and concise description of what you expected to happen.     not cost that much 

![Screenshot (83)](https://user-images.githubusercontent.com/119485826/204743567-015234d1-6b43-42ef-8378-a7d495f4d1de.png)
 Single Player
- The_Vault Version [e.g. 1.0.1]

**Comment by arwilson51** [comment] 2022-11-30 17:36
... what? have you not used a stonecutter before? its not 64 for 1, its just the options for the deepslate to turn into a wall. you just happened to put 64 in there. if you put 1 in you get the same result. Might as well just close this to lighten the load of the actual developers
![image](https://user-images.githubusercontent.com/119262684/204867977-ce9889c4-99e6-4033-bb3c-18a0ed2e77fb.png)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/119262684/204868540-6c14c9dd-d848-451f-9a7b-27ead6abdc91.gif)

(I also tested this in survival unrecorded and it still works the exact same way)

**Comment by jmilthedude** [comment] 2022-11-30 18:15
As mentioned by @arwilson51 this not a bug. Closing.

**Closed as completed by jmilthedude** 2022-11-30 18:15 UTC
