### ISSUE TITLE
Bounty crashes the game

### ISSUE THREAD

**Issue by joopooo** [Iskallia/Vault-public#1126] opened 2022-11-29 15:16 UTC
**Describe the bug**
Clicking onto a specifig Completion Bounty in the Bountytable crashes the whole game.

**To Reproduce**
1.Rerole a Bounty or complete one and wait for a new one
2.Click on the new Bounty
3.Minecraft freezes and crashes

**Expected behavior**
I expected that i would be able to see the bounty and/or reroll it/ accept it.

**Screenshots or Crash Report**
The game crashed whilst mousereleased event handler
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Component.m_7451_(net.minecraft.network.chat.FormattedText$StyledContentConsumer, net.minecraft.network.chat.Style)" because "$$4" is null
Exit-Code:-1

**Info (please complete the following information):**
- World Type: Singleplayer with Datapack generation
- The_Vault Version 1.18.2 alpha-0.0.1

**Additional context**
Its only one specifig Bounty (Completion Bounty) which now is a dead bounty in my table because interacting with it crashes the game. Other rerolls and new Bountys work fine.

**Comment by jmilthedude** [comment] 2022-11-29 15:17
duplicate of #1114 fixed in next update.

**Closed as completed** 2022-11-29 15:17 UTC
