### ISSUE TITLE
Vault Timer not counting down?

### ISSUE THREAD

**Issue by KaiHD** [Iskallia/Vault-public#85] opened 2021-03-26 18:59 UTC
Just ran my first common vault but when I go into the vault the timer stays at 25mins and does not count down
- Playing SP, newest version as per discord and using MultiMC to run

**Comment by BONNe** [comment] 2021-03-26 19:02
The issue is fixed in the latest Vault version.
You should update your client with the newest VaultHunter version (1.0.1)

**Comment by KaiHD** [comment] 2021-03-26 19:08
Sorry I didn't mean to close this
I'm using the latest version as per discord, but this downloads as version 1.0 (the one iskall posted yesterday afternoon)

**Closed** 2021-03-26 19:10 UTC

**Comment by KaiHD** [comment] 2021-03-26 19:23
Ignore this, worked it out, the mod didn’t update through the discord link but manually updated through curseforge
