### ISSUE TITLE
SpaceX cannot be crafted on a stonecutter

### ISSUE THREAD

**Issue by MrFierceWolf** [Iskallia/Vault-public#889] opened 2022-04-06 21:44 UTC
Whenever you try to craft any SpaceX block from a stonecutter it just glitches and doesn't craft.

World Type: Server

**Comment by bmemike** [comment] 2022-04-07 03:43
Dupe of #478

**Comment by MrFierceWolf** [comment] 2022-04-07 21:02
Well then why hasn't it been fixed

**Comment by bmemike** [comment] 2022-04-08 01:53
Because:
1) There's only so much the development team can work on at any given time and
2) It's not a priority

**Closed as completed** 2022-04-08 21:14 UTC
